### ISSUE TITLE
OpenAPIについて

### ISSUE THREAD

**Issue by ktaroabobon** [givery-bootcamp/dena-2024-team4#2]
- Schema定義をどこにおいておくか

**Comment by ktaroabobon** [comment]
バックエンドに委ねられたので、方向性としては二通り
1. swaggerを書いてそこからmake genする
2. Goでinterfaceを書いてmake genしてswaggerを生成させる

個人的には1はやったことあるけど2はない

**Comment by ktaroabobon** [comment]
### 1. Swaggerを直接書いてからコードを生成する

#### メリット
- **設計主導の開発 (Design-First)**: API設計を先行させ、その設計に基づいてバックエンドやフロントエンドのコードを生成。これにより、API仕様が明確になり、フロントエンドとバックエンド間の認識のズレを防げる。
- **クリアな契約書として機能**: Swaggerファイルがフロントエンドとバックエンド間の契約書として機能し、双方がAPIスペックに従って作業を進めやすくなる。
- **ツールエコシステムの利用**: Swaggerは多くのツールに対応しており、自動でクライアントライブラリやサーバースタブ、APIドキュメントを生成できる。

#### デメリット
- **柔軟性の欠如**: APIの変更が必要な場合、Swaggerファイルを更新し、それに基づいて再びコードを生成する必要がある。初期開発段階で頻繁に変更が必要な場合、手間がかかる。
- **学習曲線**: Swaggerスペックの書き方を理解し、適切にドキュメントを作成するためには時間が必要。

### 2. Goでインターフェースを書いてからSwaggerを生成する

#### メリット
- **コード主導の開発 (Code-First)**: 実際のコードを基にしてAPIドキュメント（Swagger）を生成するため、開発者はコーディングに集中でき、ドキュメントの整合性が保たれる。
- **開発の迅速化**: APIの実装を直接コーディングでき、プロジェクトの初期段階で迅速に進められる。
- **実装とドキュメントの同期**: コードとSwaggerドキュメントが常に同期されるため、ドキュメントの齟齬を心配する必要がない。

#### デメリット
- **自動生成されたドキュメントの品質**: コードから生成されるドキュメントは、手動で記述されるものに比べて詳細さや説明が不足することがある。
- **ツール依存性**: コードからSwaggerを生成するためのツールやライブラリが必要。これらのツールがプロジェクトの要件に完全に適合しているとは限らず、カスタマイズが必要になることがある。

**Comment by ktaroabobon** [comment]
1で必要になりそうなの
- [swagger](https://swagger.io/)
- [openapi-generator](https://github.com/OpenAPITools/openapi-generator)
- [swagger UI](https://swagger.io/tools/swagger-ui/)

**Comment by aohana-AO** [comment]
1でいこ！

**Comment by ktaroabobon** [comment]
ディレクトリはroot/docsで

**Comment by ktaroabobon** [comment]
openapi versionは3.1.0で

https://swagger.io/specification/
